/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    container: {
      center: true,
      padding: { DEFAULT: '1rem', sm: '1.5rem', lg: '2rem' },
      screens: { '2xl': '1280px' },
    },
    extend: {
      colors: {
        /* Identite MAKALO */
        nuit: {
          DEFAULT: '#0F2B5B',
          50: '#EEF3FB',
          100: '#D9E4F5',
          200: '#B3C8EA',
          300: '#7F9FD6',
          400: '#4A73B8',
          500: '#245097',
          600: '#173C77',
          700: '#0F2B5B',
          800: '#0B2047',
          900: '#071633',
        },
        orange: {
          DEFAULT: '#FF7A30',
          50: '#FFF3EB',
          100: '#FFE3D1',
          200: '#FFC5A3',
          300: '#FFA470',
          400: '#FF8B4A',
          500: '#FF7A30',
          600: '#EE5F0F',
          700: '#C24A09',
          800: '#963A0B',
          900: '#712D0B',
        },
        ivoire: { DEFAULT: '#FFF7ED', 100: '#FFFBF5', 200: '#FFF7ED', 300: '#FDEEDD' },
        doux: {
          DEFAULT: '#64748B',
          100: '#F1F5F9',
          200: '#E2E8F0',
          300: '#CBD5E1',
          400: '#94A3B8',
          500: '#64748B',
          600: '#475569',
        },

        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        success: { DEFAULT: '#15803D', foreground: '#FFFFFF', soft: '#DCFCE7' },
        warning: { DEFAULT: '#B45309', foreground: '#FFFFFF', soft: '#FEF3C7' },
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        xl: 'calc(var(--radius) + 4px)',
        '2xl': 'calc(var(--radius) + 8px)',
      },
      boxShadow: {
        card: '0 1px 2px 0 rgb(15 43 91 / 0.04), 0 4px 16px -4px rgb(15 43 91 / 0.08)',
        'card-hover': '0 2px 4px 0 rgb(15 43 91 / 0.06), 0 12px 28px -8px rgb(15 43 91 / 0.16)',
        pop: '0 8px 32px -8px rgb(15 43 91 / 0.24)',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'fade-in-up': { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'pop-in': { '0%': { transform: 'scale(0.85)' }, '60%': { transform: 'scale(1.12)' }, '100%': { transform: 'scale(1)' } },
        shimmer: { '100%': { transform: 'translateX(100%)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in-up': 'fade-in-up 0.32s ease-out both',
        'pop-in': 'pop-in 0.28s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
